# fly.toml app configuration file generated for 2-6-blue-frost-132 on 2024-02-09T15:51:37-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '2-6-blue-frost-132'
primary_region = 'sea'

[build]

[env]
  PORT = '3000'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
